grafana:
  rpm_url:  https://dl.grafana.com/oss/release/grafana-11.6.10-1.x86_64.rpm
  rpm_name: grafana-11.6.10-1.x86_64.rpm
  deb_url:  https://dl.grafana.com/oss/release/grafana_11.6.10_amd64.deb
  deb_name: grafana_11.6.10_amd64.deb
grafana-arm64:
  rpm_url: 
  rpm_name: 
  deb_url:  https://dl.grafana.com/oss/release/grafana_11.6.10_arm64.deb
  deb_name: grafana_11.6.10_arm64.deb
